# Quy ??nh m?c ?? log và n?i xu?t (Console, File)
log4j.rootLogger=INFO, stdout, file

# C?u hình xu?t ra Console
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout

# C?u hình ghi vào file
log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.File=logs/app_log.log